package com.example.secrets_manager.core.models;

public enum AuditAction {
  GENESIS,

  USER_CREATE,
  USER_DELETE,
  USER_PASSWORD_UPDATE,
  USER_ROLES_UPDATE,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FAILED,
  USER_LOGOUT,
  USER_TOKEN_REFRESH_SUCCESS,
  USER_TOKEN_REFRESH_FAILED,

  AUTHORIZATION_UPDATE,
  ACCESS_DENIED,

  SECRET_GROUP_CREATE,
  SECRET_GROUP_DELETE,
  SECRET_GROUP_UPDATE,

  SECRET_CREATE,
  SECRET_DELETE,
  SECRET_UPDATE,
  SECRET_READ,
  SECRET_MASTER_KEY_UPGRADED,

  MASTER_KEY_PROMOTED,
  MASTER_KEY_ACTIVATE,
  MASTER_KEY_DEACTIVATE,

  DEK_ROTATE
}
