package com.example.secrets_manager.core.models;

public enum AuditAction {
  GENESIS,

  USER_CREATE,
  USER_DELETE,
  USER_PASSWORD_UPDATE,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FAILED,

  AUTHORIZATION_GRANT,
  AUTHORIZATION_REVOKE,
  ACCESS_DENIED,

  SECRET_GROUP_CREATE,
  SECRET_GROUP_DELETE,
  SECRET_GROUP_UPDATE,

  SECRET_CREATE,
  SECRET_DELETE,
  SECRET_UPDATE,
  SECRET_READ,

  MASTER_KEY_ACTIVATE,
  MASTER_KEY_DEACTIVATE,

  DEK_ROTATE
}
