spring:
  application:
    name: secrets-manager
  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none # Flyway handles schema management
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      - classpath:com/example/secrets_manager/db/migration

jwt:
  secret-key:
    public: ${JWT_PUBLIC_KEY}
    private: ${JWT_PRIVATE_KEY}
  expiration:
    access: 300000
    refresh: 2592000000

bootstrap:
  admin:
    username: ${BOOTSTRAP_USERNAME}
    password: ${BOOTSTRAP_PASSWORD}
